version: "3.5"

services:
  fastapi:
    image: fastapi_app_fmw_dev
    volumes: 
      - ./fastapi_app:/fastapi_app
      # - ./vectorizer:/fastapi_app/vectorizer
      # - ./22full-metal-weaviate/:/22full-metal-weaviate/
      # - ./23full-metal-monad/:/23full-metal-monad/
    ports:
      - 8002:8002
    env_file:
      - full_metal_weaviate.env
    networks:
      - shared-network
      
  # weaviate:
  #   image: semitechnologies/weaviate:1.24.12
  #   ports:
  #     - 8080:8080
  #     - 50051:50051
  #   volumes:
  #     - ./05data_shokunin/weaviate_data_21:/var/lib/weaviate
  #   env_file:
  #     - shokunin_var.env
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 25
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     CLUSTER_HOSTNAME: 'node1'
  #     BACKUP_S3_BUCKET: 'shokunin-backup'
  #     ENABLE_MODULES: 'backup-s3'
  #     AUTHENTICATION_APIKEY_ENABLED: 'true'
  #     AUTHORIZATION_ADMINLIST_ENABLED: 'true'
  #   networks:
  #     - shared-network
      
networks:
  shared-network:
    external: true

