# 
FROM python:3.9
RUN apt-get update 
RUN apt-get install -y vim
 
# 
WORKDIR /fastapi_app

# 
COPY ./requirements.txt /fastapi_app/requirements.txt

# 
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /fastapi_app/requirements.txt

# self generated for local dev
COPY ./cert.pem /fastapi_app/cert.pem
COPY ./key.pem /fastapi_app/key.pem
# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--log-level", "debug", "--reload", "--reload-dir", "/fastapi_app/app", "--ssl-keyfile", "/fastapi_app/key.pem", "--ssl-certfile", "/fastapi_app/cert.pem", "--ws", "websockets"]

