# 
FROM python:3.9
RUN apt-get update 
RUN apt-get install -y vim
 
# 
WORKDIR .

# 
COPY ./requirements.txt ./requirements.txt

# 
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

# self generated for local dev
COPY ./cert.pem ./cert.pem
COPY ./key.pem ./key.pem
# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug", "--reload", "--reload-dir", "./app", "--ssl-keyfile", "./key.pem", "--ssl-certfile", "./cert.pem", "--ws", "websockets"]

